### PR TITLE
Fix focus issue and add flexibility `enableUserSelectHack` via props from GridItem

### PR DESCRIPTION
**Pull request by nikhil892**
**Target problem**:
Whenever there is an input and a draggable list and the user types something, the focus is lost from the input field because the `enableUserSelectHack` is removing some styles

**Solution description**:
This flag is now set as `false` when using the `GridLayout` component. This will fix performance issues and also allow this flag control via props.

### CODE REVIEW

**Comment by nikhil892** [comment]
@palashkaria @Mayank1791989 This has a fix that I have implemented in the `processGridItem` function. I have also commented that on the actual PR as well. This seems to solve the problem of focus. Also not making the version changes like @Mayank1791989 suggested in #1

**Comment by Mayank1791989** [comment]
@nikhil892 Lot of changes in the PR, looks like base branch `master` and the branch from which `temp-fix` is forked are different.

**Comment by nikhil892** [comment]
@Mayank1791989 I'll merge the master from the main repo.. Could be that

**Comment by nikhil892** [comment]
@Mayank1791989 Merged the master changes from the main repo

**Review by Mayank1791989 — APPROVED** [review]

**Pull request merged**
