### PR TITLE
Enable user select hack fix

### PR DESCRIPTION
**Pull request by nikhil892**
**Target problem**:
Whenever there is an input and a draggable list and the user types something, the focus is lost from the input field because the `enableUserSelectHack` is removing some styles

**Solution description**:
This flag is now set to true to avoid such problem and is added to prop allowing this to be controllable. Default value is set to `true`.

### CODE REVIEW

**Review by palashkaria — APPROVED** [review]

**Comment by palashkaria** [comment]
@nikhil892 add a version update & build lib files too.

**Comment by nikhil892** [comment]
@palashkaria Yep! Will do

**Review by Mayank1791989 — APPROVED** [review]

**Comment by Mayank1791989** [comment]
Let's use  v0.17.1 instead of master for base branch.

**Comment by nikhil892** [comment]
Created a cleaner fix

**Pull request closed without merging**
